name: Notify Parent Repository

on:
  push:
    branches: [ main ]
  
  # Also trigger on releases
  release:
    types: [published]

jobs:
  notify-parent:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger parent repository sync
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PARENT_REPO_TOKEN }}
        repository: HadiAlizade77/zadix-infra-ansible
        event-type: landing-page-updated
        client-payload: |
          {
            "landing_page_commit": "${{ github.sha }}",
            "landing_page_ref": "${{ github.ref }}",
            "pusher": "${{ github.actor }}"
          }